// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const SessionType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SessionFocus: "focus",
    SessionShortBreak: "short_break",
    SessionLongBreak: "long_break",
};

/**
 * @readonly
 * @enum {string}
 */
export const TimerState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateStopped: "stopped",
    StateRunning: "running",
    StatePaused: "paused",
};

export class TimerTick {
    /**
     * Creates a new TimerTick instance.
     * @param {Partial<TimerTick>} [$$source = {}] - The source object to create the TimerTick.
     */
    constructor($$source = {}) {
        if (!("remaining_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remaining_seconds"] = 0;
        }
        if (!("total_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_seconds"] = 0;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {TimerState}
             */
            this["state"] = TimerState.$zero;
        }
        if (!("session_type" in $$source)) {
            /**
             * @member
             * @type {SessionType}
             */
            this["session_type"] = SessionType.$zero;
        }
        if (!("formatted_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["formatted_time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimerTick instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TimerTick}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimerTick(/** @type {Partial<TimerTick>} */($$parsedSource));
    }
}
