// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Pause() {
    return $Call.ByID(3995614378);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Play() {
    return $Call.ByID(3972373962);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Reset() {
    return $Call.ByID(3893861207);
}

/**
 * @param {string} sType
 * @returns {$CancellablePromise<void>}
 */
export function SetSessionType(sType) {
    return $Call.ByID(3510599804, sType);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Skip() {
    return $Call.ByID(178849663);
}
